### ISSUE TITLE
Can't access files to add background

### ISSUE THREAD

**Issue by frdbr** [flathub/org.jitsi.jitsi-meet#21] opened 2021-06-22 03:19 UTC
Choosing _select background_ option and then the _Add background_ option one can't see the files in the computer. 

![image](https://user-images.githubusercontent.com/77309092/122857774-6f39ae80-d2ef-11eb-9a1d-441d4f4d4048.png)

**Comment by hfiguiere** [comment] 2021-06-22 03:29
The package doesn't grant access to the filesystem.

Until the flatpak is fixed, this can be overridden with a tool like Flatseal, or with the command line.

**Comment by ananace** [comment] 2021-06-22 06:56
I'd call this a duplicate of #20 
Since https://github.com/electron/electron/pull/19159 seems to be planned for october with 14.0 though I'm guessing it might be reasonable to add a read-only permission for the home directory

**Closed** 2021-06-22 06:59 UTC
Labels: bug, duplicate

**Comment by vchernin** [comment] 2021-06-22 15:40
@ananace FYI Electron 14 seems to be scheduled to release on August 31st. https://www.electronjs.org/docs/tutorial/electron-timelines
Hopefully Jitsi updates quickly after that.

**Comment by mccarthyryanc** [comment] 2022-01-23 21:51
This issue still exists for me as of version `2022.1.1`. But a temporary fix was to run with the `--filesystem` option:
```bash
flatpak run --filesystem=/path/to/pictures:ro org.jitsi.jitsi-meet
```
and then add the backgrounds. After that, app could be launched normally with the backgrounds saved.

**Comment by vchernin** [comment] 2022-01-24 07:55
@mccarthyryanc what distro, and `xdg-desktop-portal` version? It works for me on Fedora 35 with `xdg-desktop-portal-1.12.1-1.fc35.x86_64`

**Comment by mccarthyryanc** [comment] 2022-01-27 04:31
@vchernin I'm on Pop!_OS 20.04 and `xdg-desktop-portal-1.6.0-1`, so maybe a little too old?

**Comment by vchernin** [comment] 2022-01-27 04:34
Unfortunately that is possible, 1.6.0 was released over 2 years ago. I assume it will work in newer Pop os releases.

**Comment by mccarthyryanc** [comment] 2022-01-27 04:40
That's okay, thanks for the follow up! I have a fix for now and it sounds like it should work post-upgrade.
